### ISSUE TITLE
Struggling to extend type in nodejs service

### ISSUE THREAD

**Issue by ryannealmes** [Gusto/apollo-federation-ruby#24]
I have been trying to get this working for the past day and have hit a blocker. Any help would be appreciated.

I have created a dummy service - customer service (in nodejs) - and another dummy service - schedule service (in ruby). I want to create a one to many relationship between customer and schedule. i.e. a customer can have many schedules.

I have managed to get queries like the following working

```graphql
{
  schedules {
    id
    time
    customer {
      id
      schedules {
        id
        time
        customer {
          id
        }
      }
    }
  }
}

```
So I feel like I have setup everything up in my service correctly. When I call things in the gateway things partially work as well. For example

```graphql
{
  customers {
    id
    name
    # schedules {
    #   id
    #   # time
    # }
  }
  schedules {
    id
    time
    customer {
      id
      name
      schedules {
        id
      }
    }
  }
}

```
As soon as I add in the commented out bit I get the following error.

```json
{
  "errors": [
    {
      "message": "500: Internal Server Error",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "http://localhost:3000/graphql",
          "status": 500,
          "statusText": "Internal Server Error",
          "body": {
            "error": {
              "message": "no implicit conversion of #<Class:0x00007f81638ce970> into Hash",
              "backtrace": [
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:524:in `block in resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:661:in `block in with_extensions'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:680:in `block (2 levels) in run_extensions_before_resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:683:in `run_extensions_before_resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:680:in `block in run_extensions_before_resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field_extension.rb:50:in `resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:678:in `run_extensions_before_resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:660:in `with_extensions'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/field.rb:504:in `resolve'",
                "/Users/ryanme/src/ap-apollo-integration-example/scheduling-service/app/graphql/types/base_field.rb:13:in `resolve_field'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/member/instrumentation.rb:80:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/member/instrumentation.rb:80:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/field.rb:248:in `resolve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:321:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema/middleware_chain.rb:38:in `invoke'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:129:in `block in resolve_field'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `block in trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:76:in `call_tracers'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:128:in `resolve_field'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:85:in `each'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:85:in `resolve_selection'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `block in trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:76:in `call_tracers'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/execute.rb:31:in `begin_query'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:112:in `begin_query'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:83:in `map'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:186:in `block in instrument_and_analyze'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `block in trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:76:in `call_tracers'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/tracing.rb:62:in `trace'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:59:in `run_queries'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/execution/multiplex.rb:49:in `run_all'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema.rb:392:in `block in multiplex'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema.rb:1279:in `with_definition_error_check'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema.rb:391:in `multiplex'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/graphql-1.9.12/lib/graphql/schema.rb:368:in `execute'",
                "/Users/ryanme/src/ap-apollo-integration-example/scheduling-service/app/controllers/graphql_controller.rb:10:in `execute'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:196:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/cookies.rb:648:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:567:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:101:in `run_callbacks'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:132:in `call_app'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:28:in `block in call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:38:in `call_app'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:126:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'",
                "/Users/ryanme/.rvm/gems/ruby-2.5.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
              ]
            },
            "data": {}
          }
        },
        "exception": {
          "stacktrace": [
            "Error: 500: Internal Server Error",
            "    at RemoteGraphQLDataSource.<anonymous> (/Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:94:25)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:7:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:3:12)",
            "    at RemoteGraphQLDataSource.errorFromResponse (/Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:84:16)",
            "    at RemoteGraphQLDataSource.<anonymous> (/Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:67:34)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/ryanme/src/ap-apollo-integration-example/gateway/node_modules/@apollo/gateway/dist/datasources/RemoteGraphQLDataSource.js:7:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "customers": [
      {
        "id": "1",
        "name": "Ryan",
        "schedules": null
      },
      {
        "id": "2",
        "name": "Jackie",
        "schedules": null
      }
    ],
    "schedules": [
      {
        "id": "1",
        "time": "tomorrow",
        "customer": {
          "id": "1",
          "name": "Ryan",
          "schedules": [
            {
              "id": "1"
            },
            {
              "id": "2"
            }
          ]
        }
      },
      {
        "id": "2",
        "time": "now",
        "customer": {
          "id": "2",
          "name": "Jackie",
          "schedules": [
            {
              "id": "1"
            },
            {
              "id": "2"
            }
          ]
        }
      }
    ]
  }
}
```
I managed to replicate the error just on the scheduling service with the following query
```graphql
{
  _entities(representations: [{__typename: "Customer", id: "1"}, {__typename:"Customer", id: "2"}]) {
    __typename
  }
}
```
I am running rails 6 with the latest version of graphql-ruby and apollo-federation-ruby.

```ruby
# types/customer_type.rb
module Types
  class CustomerType < Types::BaseObject
    extend_type
    key fields: 'id'

    field :id, ID, null: false, external: true
    field :schedules, [ScheduleType], null: true

    # I simplified this method temporarily while testing
    def schedules
      [
        {
          id: 1,
          customer_id: 1,
          time: "today"
        },
        {
          id: 2,
          customer_id: 1,
          time: "tommorrow"
        }
      ]
    end
  end
end
```
```ruby
# types/customer_type.rb
module Types
  class ScheduleType < Types::BaseObject
    key fields: 'id'

    field :id, ID, null: false
    field :time, String, null: false
    field :customer, Types::CustomerType, null: true

    def self.resolve_reference(reference, context)
      Schedule.find { |schedule| schedule[:id] == reference[:id] }
    end

    def customer
      { __typename: 'Customer', id: object[:customer_id] }
    end
  end
end
```

```ruby
# schema
class SchedulingServiceSchema < GraphQL::Schema
  include ApolloFederation::Schema

  mutation(Types::MutationType)
  query(Types::QueryType)

  orphan_types Types::CustomerType
end

```
```ruby
module Types
  class QueryType < Types::BaseObject
    # Add root-level fields here.
    # They will be entry points for queries on your schema.

    # TODO: remove me
    field :test_field, String, null: false,
      description: "An example field added by the generator"
    def test_field
      "Hello World!"
    end

    field :schedules, [ScheduleType], null: false

    def schedules
      Schedule.all
    end
  end
end

```
I have 4 other services written in nodejs that are connected to my data gateway and running fine, just trying to get the ruby one to work. Any help would be appreciated.

**Comment by ryannealmes** [comment]
I have created simple demo repo to demonstrate the issue - https://github.com/ryannealmes/graphql-ruby-apollo-example

To get going:
```
bundle install
rails server
```
- Go to localhost:3000/graphiql
- Run the following query
```graphql
{
  # Commented out query does not work :(
  # _entities(representations: [
  #     {
  #       __typename: "Account",
  #       id: "1"
  #     }
  #   ]) {
  #   __typename
  # }
  customers {
    id
    name
    account {
      id
      customers {
        id
      }
    }
  }
}
```
Run it again with the commented out code.

I am hoping I just have something setup incorrectly, but I have followed the docs and I just can't for the life of me find the issue :(
Any help would be appreciated

**Comment by ryannealmes** [comment]
I have found the issue by luck. Although I don't have much experience so not really sure if this is a bug or expect

https://github.com/quick-xp/apollo-federation-sample/blob/master/review-ruby-2.4/app/graphql/types/base_field.rb#L8

The above repo had the same issue and they commented out the `resolve_field` method which fixed things. It would be great to get some input on the expected behaviour and maybe update the docs if that is what developers should do.

Thx for the awesomeness. This gem would really help us!

**Comment by rylanc** [comment]
Hi @ryannealmes. Sorry for the delay. Is this still an issue for you?

**Comment by BatuhanW** [comment]
@ryannealmes I had the same issue. Using `OpenStruct` instead of Hash fixes the issue.

```
def customer
  OpenStruct.new(__typename: 'Customer', id: object.customer_id)
end
```

**Comment by daemonsy** [comment]
Seems like there hasn't been a response to this issue for a while, so I'l close it. @ryannealmes if you're still having issues, please feel free to post back.
