### ISSUE TITLE
graphql 2.3.8 removes "warden", breaking schema composition etc

### ISSUE THREAD

**Issue by lyricsboy** [Gusto/apollo-federation-ruby#276]
A change released in the 2.3.8 version of `graphql` removed the `warden` definition from a number of places, including this one:

https://github.com/rmosolgo/graphql-ruby/compare/v2.3.7...v2.3.8#diff-e9dd0d295a58b66fabd1cf717040de5a78ade0feac6aeabae5247b5785c029ab

It looks like the internal usage of `warden` was replaced with `types` in many cases. This is [documented in the release notes](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#238-12-jul-2024), but not as a breaking change.

This is manifesting for us in CI builds as an error like the following:

```
/mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:83:in `query_type?': undefined local variable or method `warden' for #<ApolloFederation::FederatedDocumentFromSchemaDefinition...

      type == warden.root_type_for_operation('query')
              ^^^^^^
Did you mean?  warn
        from /mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:71:in `block in build_type_definition_nodes'
        from /mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:70:in `select'
        from /mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/apollo-federation-3.8.5/lib/apollo-federation/federated_document_from_schema_definition.rb:70:in `build_type_definition_nodes'
        from /mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/graphql-2.3.8/lib/graphql/language/document_from_schema_definition.rb:262:in `build_definition_nodes'
        from /mnt/ramdisk/vendor/bundle/ruby/3.2.0/gems/graphql-2.3.8/lib/graphql/language/document_from_schema_definition.rb:33:in `document'
```

**Comment by andriimosin** [comment]
This is a big blocker for us as well. Could you please merge the PR with the fix?

**Comment by palexvs** [comment]
same here

**Comment by whitethunder** [comment]
Also a problem for us. Because of [this CVE](https://github.com/advisories/GHSA-q92j-grw3-h492) we had to change `graphql` versions, but also discovered that anything `>= 2.3.8` no longer works with `apollo-federation`. We elected to go with the latest `2.2.x` version of `graphql` to work around both issues, but we are currently blocked from upgrading to anything `>= 2.3.0`.
